"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from tofupilot.v2.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ProcedureUpdateRequestBodyTypedDict(TypedDict):
    name: NotRequired[str]
    r"""New name for the procedure."""
    production_branch: NotRequired[Nullable[str]]
    r"""Branch treated as production. Pushes to this branch deploy as production; every other branch deploys as preview. Null = no branch promoted to production."""
    auto_push_enabled: NotRequired[bool]
    r"""Master switch for auto-pushing builds to linked stations. Build artifacts are always recorded; this only gates the station fan-out."""
    excluded_branch_patterns: NotRequired[List[str]]
    r"""Branches matching any of these patterns (exact name or minimatch glob, e.g. \"renovate/*\") skip preview deployments. Empty array = no exclusions."""
    root_directory: NotRequired[Nullable[str]]
    r"""Path within the linked repo to the directory holding this procedure's `pyproject.toml` (and `procedure.yaml` for framework procedures). Empty/null = repo root."""
    entry_point: NotRequired[Nullable[str]]
    r"""Entry-point path inside the procedure's package dir, relative to it. Forwarded to the CLI through the deployment manifest. Empty/null = use the framework default (openhtf/plain → main.py, pytest → \".\", yaml → procedure.yaml auto-discovery)."""


class ProcedureUpdateRequestBody(BaseModel):
    name: Optional[str] = None
    r"""New name for the procedure."""

    production_branch: Annotated[
        OptionalNullable[str], pydantic.Field(alias="productionBranch")
    ] = UNSET
    r"""Branch treated as production. Pushes to this branch deploy as production; every other branch deploys as preview. Null = no branch promoted to production."""

    auto_push_enabled: Annotated[
        Optional[bool], pydantic.Field(alias="autoPushEnabled")
    ] = None
    r"""Master switch for auto-pushing builds to linked stations. Build artifacts are always recorded; this only gates the station fan-out."""

    excluded_branch_patterns: Annotated[
        Optional[List[str]], pydantic.Field(alias="excludedBranchPatterns")
    ] = None
    r"""Branches matching any of these patterns (exact name or minimatch glob, e.g. \"renovate/*\") skip preview deployments. Empty array = no exclusions."""

    root_directory: Annotated[
        OptionalNullable[str], pydantic.Field(alias="rootDirectory")
    ] = UNSET
    r"""Path within the linked repo to the directory holding this procedure's `pyproject.toml` (and `procedure.yaml` for framework procedures). Empty/null = repo root."""

    entry_point: Annotated[
        OptionalNullable[str], pydantic.Field(alias="entryPoint")
    ] = UNSET
    r"""Entry-point path inside the procedure's package dir, relative to it. Forwarded to the CLI through the deployment manifest. Empty/null = use the framework default (openhtf/plain → main.py, pytest → \".\", yaml → procedure.yaml auto-discovery)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = [
            "name",
            "productionBranch",
            "autoPushEnabled",
            "excludedBranchPatterns",
            "rootDirectory",
            "entryPoint",
        ]
        nullable_fields = ["productionBranch", "rootDirectory", "entryPoint"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m


class ProcedureUpdateRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the procedure to update."""
    request_body: ProcedureUpdateRequestBodyTypedDict


class ProcedureUpdateRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the procedure to update."""

    request_body: Annotated[
        ProcedureUpdateRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class ProcedureUpdateResponseTypedDict(TypedDict):
    r"""Procedure updated successfully"""

    id: str
    r"""Unique identifier of the updated procedure."""


class ProcedureUpdateResponse(BaseModel):
    r"""Procedure updated successfully"""

    id: str
    r"""Unique identifier of the updated procedure."""
