"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel, Nullable
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing import Dict, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


RunUpdateMetadataMetadataTypedDict = TypeAliasType(
    "RunUpdateMetadataMetadataTypedDict", Union[str, float, bool]
)


RunUpdateMetadataMetadata = TypeAliasType(
    "RunUpdateMetadataMetadata", Union[str, float, bool]
)


class RunUpdateMetadataRequestBodyTypedDict(TypedDict):
    metadata: NotRequired[Dict[str, Nullable[RunUpdateMetadataMetadataTypedDict]]]
    r"""Custom metadata to upsert on the run. Plain object of key/value pairs. PATCH semantics: keys not present here are preserved. Pass `null` as a value to delete a key."""


class RunUpdateMetadataRequestBody(BaseModel):
    metadata: Optional[Dict[str, Nullable[RunUpdateMetadataMetadata]]] = None
    r"""Custom metadata to upsert on the run. Plain object of key/value pairs. PATCH semantics: keys not present here are preserved. Pass `null` as a value to delete a key."""


class RunUpdateMetadataRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the run to update."""
    request_body: RunUpdateMetadataRequestBodyTypedDict


class RunUpdateMetadataRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the run to update."""

    request_body: Annotated[
        RunUpdateMetadataRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class RunUpdateMetadataResponseTypedDict(TypedDict):
    r"""Run metadata updated successfully"""

    id: str
    r"""Unique identifier of the updated run."""


class RunUpdateMetadataResponse(BaseModel):
    r"""Run metadata updated successfully"""

    id: str
    r"""Unique identifier of the updated run."""
