"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class RunCreateAttachmentRequestBodyTypedDict(TypedDict):
    name: str
    r"""File name including extension (e.g. \"report.pdf\"). Used to determine content type and display name."""


class RunCreateAttachmentRequestBody(BaseModel):
    name: str
    r"""File name including extension (e.g. \"report.pdf\"). Used to determine content type and display name."""


class RunCreateAttachmentRequestTypedDict(TypedDict):
    id: str
    r"""Unique identifier of the run to attach the file to."""
    request_body: RunCreateAttachmentRequestBodyTypedDict


class RunCreateAttachmentRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the run to attach the file to."""

    request_body: Annotated[
        RunCreateAttachmentRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class RunCreateAttachmentResponseTypedDict(TypedDict):
    r"""Run attachment created successfully"""

    id: str
    r"""Unique identifier of the created attachment. Use this to reference the attachment in subsequent API calls."""
    upload_url: str
    r"""Temporary pre-signed URL to upload the file directly to storage. Send a PUT request with the raw file bytes and appropriate Content-Type header. The URL expires after 60 seconds."""


class RunCreateAttachmentResponse(BaseModel):
    r"""Run attachment created successfully"""

    id: str
    r"""Unique identifier of the created attachment. Use this to reference the attachment in subsequent API calls."""

    upload_url: str
    r"""Temporary pre-signed URL to upload the file directly to storage. Send a PUT request with the raw file bytes and appropriate Content-Type header. The URL expires after 60 seconds."""
