"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
from typing import List
from typing_extensions import Annotated, TypedDict


class UnitDeleteAttachmentRequestTypedDict(TypedDict):
    serial_number: str
    r"""Serial number of the unit. Matched case-insensitively."""
    ids: List[str]
    r"""Attachment IDs to delete"""


class UnitDeleteAttachmentRequest(BaseModel):
    serial_number: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Serial number of the unit. Matched case-insensitively."""

    ids: Annotated[
        List[str], FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Attachment IDs to delete"""


class UnitDeleteAttachmentResponseTypedDict(TypedDict):
    r"""Unit attachments deleted successfully"""

    ids: List[str]
    r"""IDs of attachments that were deleted"""


class UnitDeleteAttachmentResponse(BaseModel):
    r"""Unit attachments deleted successfully"""

    ids: List[str]
    r"""IDs of attachments that were deleted"""
