"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from tofupilot.v2.types import BaseModel
from tofupilot.v2.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class UnitCreateAttachmentRequestBodyTypedDict(TypedDict):
    name: str
    r"""File name including extension (e.g. \"calibration.pdf\"). Used to determine content type and display name."""


class UnitCreateAttachmentRequestBody(BaseModel):
    name: str
    r"""File name including extension (e.g. \"calibration.pdf\"). Used to determine content type and display name."""


class UnitCreateAttachmentRequestTypedDict(TypedDict):
    serial_number: str
    r"""Serial number of the unit to attach the file to. Matched case-insensitively."""
    request_body: UnitCreateAttachmentRequestBodyTypedDict


class UnitCreateAttachmentRequest(BaseModel):
    serial_number: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Serial number of the unit to attach the file to. Matched case-insensitively."""

    request_body: Annotated[
        UnitCreateAttachmentRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UnitCreateAttachmentResponseTypedDict(TypedDict):
    r"""Unit attachment created successfully"""

    id: str
    r"""Unique identifier of the created attachment. Use this to reference the attachment in subsequent API calls."""
    upload_url: str
    r"""Temporary pre-signed URL to upload the file directly to storage. Send a PUT request with the raw file bytes and appropriate Content-Type header. The URL expires after 60 seconds."""


class UnitCreateAttachmentResponse(BaseModel):
    r"""Unit attachment created successfully"""

    id: str
    r"""Unique identifier of the created attachment. Use this to reference the attachment in subsequent API calls."""

    upload_url: str
    r"""Temporary pre-signed URL to upload the file directly to storage. Send a PUT request with the raw file bytes and appropriate Content-Type header. The URL expires after 60 seconds."""
